import { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/utils/floating_nav";
import { IconHome, IconMessage, IconUser } from "@tabler/icons-react";
import { GridBackgroundDemo } from "@/utils/back_ground";
import { ThemeProvider } from "@/utils/theme_provider";

const monster = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blue Ocean Product",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monster.className}>
        <ThemeProvider>
          <GridBackgroundDemo>
            <FloatingNav
              navItems={[
                {
                  name: "Home",
                  link: "/",
                  icon: (
                    <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />
                  ),
                },
                {
                  name: "About",
                  link: "/about",
                  icon: (
                    <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />
                  ),
                },
                {
                  name: "Contact",
                  link: "/contact",
                  icon: (
                    <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
                  ),
                },
              ]}
            />
            {children}
          </GridBackgroundDemo>
        </ThemeProvider>
      </body>
    </html>
  );
}
